# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/logger.ipynb (unless otherwise specified).

__all__ = ['vietnam_time', 'logger', 'formatter', 'logger_handler', 'LOGGING_ROOT', 'LOGGING_FILE', 'file_handler']

# Cell
import logging
import os, sys
from datetime import datetime, timedelta
import pytz

# Cell

# config logger
logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

formatter = logging.Formatter("%(asctime)s - %(module)s %(funcName)s:%(lineno)d - [%(levelname)s] - %(message)s")

def vietnam_time(sec, what):
    """get datetime now with viet name timezone for logger"""
    vietnam_time = datetime.now(tz=pytz.timezone("Asia/Ho_Chi_Minh"))
    return vietnam_time.timetuple()


logging.Formatter.converter = vietnam_time

# set up stream logging handler
# streamhanlder is the log will display on your console
logger_handler = logging.StreamHandler(sys.stdout)
logger_handler.setFormatter(formatter)
logger.addHandler(logger_handler)


# setup for saving log to file
LOGGING_ROOT = os.path.join(os.getcwd(), "logs")
os.makedirs(LOGGING_ROOT, exist_ok=True)
LOGGING_FILE = os.path.join(LOGGING_ROOT, '{:%Y-%m-%d}.log'.format(datetime.now()))

file_handler = logging.FileHandler(LOGGING_FILE)
file_handler.setFormatter(formatter)
logger.addHandler(file_handler)

# Cell
logger.info(f"All logs will be saved in {LOGGING_FILE}")
